spring:
  application:
    name: dprofile

  logging:
    level:
      org.springframework.security: DEBUG

  datasource:
    url: jdbc:postgresql://localhost:5432/dprofiledev
    username: postgres
    password: mydatabase
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    schemas: public
    baseline-on-migrate: true
    baseline-description: Dprofile Project
    locations: classpath:db/migration/default
    continue-on-fail: false